name: Docker CI/CD

on:
  push:
    branches:
      - master
    tags:
      - version-**

jobs:
  run-unittest-and-push-to-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest
      -
        name: Run unit tests
        run: python -m pytest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Print branch name
        run: echo "Branch name = ${{ github.ref_name }}"
      -
        name: Build and push
        env:
          # Tag name == Branch name
          TAG_NAME: ${{ github.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}
