name: Docker CI/CD

on:
  push:
    branches:
      - master
      - enhance_webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd python-webservice-demo
          pip install -r requirements.txt
          pip install -e .
      -
        name: Run unit tests
        run: python -m pytest --import-mode=append tests/
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Print branch name
        run: echo "Branch name = ${{ github.ref_name }}"
      -
        name: Build and push
        env:
          TAG_NAME: ${{ github.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}
