name: Docker CI/CD

on:
  push:
    branches:
      - master
      - enhance_webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Print branch name
        run: echo "Branch name = ${{ github.ref_name }}"
      -
        name: Build and push
        env:
          TAG_NAME: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}
