name: Run Tests and Deploy

on:
  push:
    branches:
      - master
      - next-version
    tags:
      - version-**

jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch/Tag name = ${{ github.ref_name }}"
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest
      -
        name: Run unit tests
        run: python -m pytest
  deploy-to-server:
    # Only for master.
    if: github.ref_name == 'master'
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
  create-docker-image:
    # Only for app version tags.
    if: ${{ startsWith(github.ref_name, 'version-') }}
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Docker image
        env:
          TAG_NAME: ${{ github.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}